---
version: "3.7"
services:
  builder:
    build:
      context: ./builder/
    volumes:
      - app:/opt/app

  production:
    build:
      context: ./production/
    ports:
      - "80:8080"
    volumes:
      - app:/opt/app
    depends_on:
      - builder

volumes:
  app: