---
version: "3.7"
services:
  builder:
    build:
      context: builder/
    volumes:
      - app:/opt/app

  production:
    build:
      context: production/
    ports:
      - "80:8080"
    volumes:
      - app:/opt/apache-tomcat-10.0.23/webapps
#    depends_on:
      - builder

volumes:
  app: